name: Host Angular app in GitHub 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: 14.15
    - name: npm dependencies
      run: npm install
    - name: install angular
      run : npm install -g @angular/cli
    - name: Build
      run: ng build --output-path docs --base-href /ProyectoLSL/
    - name: copying files
      run: cp /home/runner/work/ProyectoLSL/ProyectoLSL/docs/index.html /home/runner/work/ProyectoLSL/ProyectoLSL/404.html
    - name: git branch
      run: git branch
