name: Host Angular app in GitHub 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
          node-version: 14.15
    - name: npm dependencies
      run: npm install     
    - name: Build
      run: npm run build -- --prod
